/** @type {import('tailwindcss').Config} */
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  darkMode: ["class"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "SF Pro Text",
          "SF Pro Display",
          "Inter",
          ...defaultTheme.fontFamily.sans,
        ],
      },
      fontSize: {
        display: [
          "34px",
          {
            lineHeight: "41px",
            letterSpacing: "0",
            fontWeight: "700",
          },
        ],
        heading: [
          "22px",
          {
            lineHeight: "28px",
            letterSpacing: "0",
            fontWeight: "600",
          },
        ],
        body: [
          "17px",
          {
            lineHeight: "22px",
            letterSpacing: "0",
            fontWeight: "400",
          },
        ],
        ui: [
          "15px",
          {
            lineHeight: "20px",
            letterSpacing: "0",
            fontWeight: "500",
          },
        ],
        label: [
          "13px",
          {
            lineHeight: "18px",
            letterSpacing: "0",
            fontWeight: "600",
          },
        ],
        data: [
          "28px",
          {
            lineHeight: "34px",
            letterSpacing: "0",
            fontWeight: "700",
          },
        ],
      },
      spacing: {
        micro: "4px",
        tag: "6px",
        item: "8px",
        control: "12px",
        component: "16px",
        card: "24px",
        panel: "32px",
        page: "40px",
        section: "40px",
        "control-mini": "28px",
        "control-small": "32px",
        target: "44px",
        "control-large": "52px",
        layout: "48px",
        "control-xl": "64px",
        spacious: "64px",
        island: "14px",
        block: "24px",
        "sidebar-inset": "16px",
        "app-gutter": "24px",
        "content-gutter": "24px",
        "app-rail": "72px",
        "sidebar-collapsed": "72px",
        "sidebar-expanded": "288px",
        search: "240px",
        "search-compact": "220px",
        "number-field": "80px",
        inspector: "420px",
        menu: "160px",
        popover: "320px",
      },
      maxWidth: {
        content: "1440px",
        readable: "768px",
        form: "440px",
        inspector: "420px",
        "detail-value": "12rem",
        title: "300px",
        chip: "120px",
        "sheet-sm": "360px",
        "sheet-md": "560px",
        "modal-lg": "860px",
        "modal-xl": "1024px",
        "viewport-safe": "92vw",
      },
      maxHeight: {
        overlay: "92vh",
        "overlay-body": "calc(92vh - 168px)",
        "overlay-detail-body": "calc(92vh - 104px)",
      },
      minWidth: {
        "table-sm": "640px",
        "table-lg": "1120px",
        "status-trigger": "138px",
        "status-menu": "180px",
      },
      gridTemplateColumns: {
        overview: "minmax(0, 1fr) 320px",
        inspector: "minmax(0, 1fr) 420px",
        "job-detail": "minmax(0, 1fr) 280px",
        settings: "minmax(0, 1fr) 260px",
        "signal-filters":
          "minmax(220px, 1.5fr) repeat(7, minmax(140px, 1fr)) auto",
      },
      colors: {
        primary: {
          DEFAULT: "hsl(var(--primary))",
          hover: "hsl(var(--primary-hover))",
          foreground: "hsl(var(--primary-foreground))",
          50: "#EAF4FF",
          100: "#D8ECFF",
          200: "#B8DCFF",
          300: "#7EB6F2",
          400: "#3D8FE0",
          500: "#0066CC",
          600: "#0055B8",
          700: "#004A99",
          800: "#003A78",
          900: "#002A57",
          950: "#001A45",
        },
        action: {
          DEFAULT: "hsl(var(--action))",
          hover: "hsl(var(--action-hover))",
          muted: "hsl(var(--action-muted))",
          foreground: "hsl(var(--action-foreground))",
          50: "#EAF4FF",
          100: "#D8ECFF",
          200: "#B8DCFF",
          300: "#7EB6F2",
          400: "#3D8FE0",
          500: "#0066CC",
          600: "#0055B8",
          700: "#004A99",
          800: "#003A78",
          900: "#002A57",
          950: "#001A45",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "#F2F2F7",
          100: "#E5E5EA",
          200: "#D1D1D6",
          300: "#C7C7CC",
          400: "#AEAEB2",
          500: "#8E8E93",
          600: "#636366",
          700: "#48484A",
          800: "#3A3A3C",
          900: "#1D1D1F",
          950: "#000000",
        },
        tertiary: {
          50: "#F2F2F7",
          100: "#E5E5EA",
          200: "#D1D1D6",
          300: "#C7C7CC",
          400: "#AEAEB2",
          500: "#8E8E93",
          600: "#636366",
          700: "#48484A",
          800: "#3A3A3C",
          900: "#1D1D1F",
          950: "#000000",
        },
        active: {
          50: "#EAF4FF",
          100: "#D8ECFF",
          200: "#B8DCFF",
          300: "#7EB6F2",
          400: "#3D8FE0",
          500: "#0066CC",
          600: "#0055B8",
          700: "#004A99",
          800: "#003A78",
          900: "#002A57",
          950: "#001A45",
        },
        surface: {
          DEFAULT: "hsl(var(--surface))",
          elevated: "hsl(var(--surface-elevated))",
          raised: "hsl(var(--surface-raised))",
          chrome: "hsl(var(--surface-chrome))",
          subtle: "hsl(var(--surface-subtle))",
          muted: "hsl(var(--surface-muted))",
        },
        block: {
          DEFAULT: "hsl(var(--block))",
          subtle: "hsl(var(--block-subtle))",
          border: "hsl(var(--block-border))",
        },
        control: {
          DEFAULT: "hsl(var(--control))",
          hover: "hsl(var(--control-hover))",
          selected: "hsl(var(--control-selected))",
          border: "hsl(var(--control-border))",
        },
        island: {
          DEFAULT: "hsl(var(--island))",
          hover: "hsl(var(--island-hover))",
          selected: "hsl(var(--island-selected))",
          border: "hsl(var(--island-border))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar))",
          border: "hsl(var(--sidebar-border))",
        },
        premium: {
          athens: "hsl(var(--neutral-athens))",
          shark: "hsl(var(--neutral-shark))",
          graphite: "hsl(var(--premium-graphite))",
          blue: "hsl(var(--premium-blue))",
          indigo: "hsl(var(--premium-indigo))",
          purple: "hsl(var(--premium-purple))",
        },
        grouped: {
          DEFAULT: "hsl(var(--background-grouped))",
          secondary: "hsl(var(--background-grouped-secondary))",
          tertiary: "hsl(var(--background-grouped-tertiary))",
        },
        text: {
          primary: "hsl(var(--text-primary))",
          secondary: "hsl(var(--text-secondary))",
          muted: "hsl(var(--text-muted))",
          quaternary: "hsl(var(--text-quaternary))",
          placeholder: "hsl(var(--text-placeholder))",
          inverted: "hsl(var(--text-inverted))",
        },
        link: {
          DEFAULT: "hsl(var(--link))",
          hover: "hsl(var(--link-hover))",
        },
        fill: {
          DEFAULT: "hsl(var(--fill))",
          secondary: "hsl(var(--fill-secondary))",
          tertiary: "hsl(var(--fill-tertiary))",
          quaternary: "hsl(var(--fill-quaternary))",
        },
        border: {
          DEFAULT: "hsl(var(--border))",
          subtle: "hsl(var(--border-subtle))",
          strong: "hsl(var(--border-strong))",
        },
        separator: {
          DEFAULT: "hsl(var(--separator))",
          opaque: "hsl(var(--separator-opaque))",
        },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: {
          DEFAULT: "hsl(var(--background))",
          grouped: "hsl(var(--background-grouped))",
          "grouped-secondary": "hsl(var(--background-grouped-secondary))",
          "grouped-tertiary": "hsl(var(--background-grouped-tertiary))",
        },
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          muted: "hsl(var(--destructive-muted))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          muted: "hsl(var(--success-muted))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          muted: "hsl(var(--warning-muted))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        material: {
          "ultra-thin": "hsl(var(--material-ultra-thin))",
          thin: "hsl(var(--material-thin))",
          regular: "hsl(var(--material-regular))",
          thick: "hsl(var(--material-thick))",
          liquid: "hsl(var(--material-liquid))",
          vibrant: "hsl(var(--material-vibrant))",
          chrome: "hsl(var(--material-chrome))",
          border: "hsl(var(--material-border))",
        },
      },
      borderRadius: {
        island: "20px",
        block: "16px",
        control: "12px",
        item: "8px",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        block:
          "0 8px 24px -18px hsl(var(--block-shadow)), 0 2px 8px -6px hsl(var(--block-shadow))",
        material:
          "0 10px 30px -10px hsl(var(--material-shadow)), 0 4px 12px -6px hsl(var(--material-shadow))",
        premium:
          "0 18px 48px -18px hsl(var(--premium-shadow)), 0 8px 20px -12px hsl(var(--premium-shadow))",
      },
      transitionDuration: {
        "motion-instant": "0ms",
        "motion-fast": "120ms",
        motion: "180ms",
        "motion-medium": "220ms",
        "motion-disclosure": "240ms",
        "motion-slow": "300ms",
      },
      transitionDelay: {
        "motion-label": "90ms",
      },
      transitionTimingFunction: {
        "motion-standard": "cubic-bezier(0.2, 0, 0, 1)",
        "motion-emphasized": "cubic-bezier(0.16, 1, 0.3, 1)",
        "motion-exit": "cubic-bezier(0.4, 0, 1, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
