import type { Application, Job, Radar, RadarFilters, RadarWeights } from "./types";

export const DEFAULT_FILTERS: RadarFilters = {
  verifiedOnly: false,
  minSpent: null,
  minHireRate: null,
  maxProposals: null,
  maxAgeHours: null,
  expertiseLevels: [],
  countriesInclude: [],
  countriesExclude: [],
  includeTags: [],
  excludeTags: [],
  minBudget: null,
  hourlyMin: null,
  hourlyMax: null,
  hideApplied: false,
  minScore: null,
};

export const DEFAULT_WEIGHTS: RadarWeights = {
  freshness: 0.25,
  lowProposals: 0.15,
  trust: 0.2,
  hireRate: 0.1,
  budget: 0.1,
  expertise: 0.1,
  geo: 0.05,
  stack: 0.05,
};

export const seedRadars: Radar[] = [
  {
    id: "radar-1",
    name: "GHL + Make",
    status: "active",
    schedule: { frequency: "daily", hourOfDay: 9 },
    notifications: {
      email: { enabled: true, to: "ops@example.com" },
      plugin: { enabled: false },
    },
    filters: {
      ...DEFAULT_FILTERS,
      verifiedOnly: true,
      includeTags: ["ghl", "make"],
      maxProposals: 10,
      hourlyMin: 20,
      hourlyMax: 80,
      countriesInclude: ["United States", "Canada", "Poland"],
    },
    weights: { ...DEFAULT_WEIGHTS },
    lastRunAt: null,
    lastResultCount: null,
  },
  {
    id: "radar-2",
    name: "Shopify fixes",
    status: "paused",
    schedule: { frequency: "hourly" },
    notifications: {
      email: { enabled: false },
      plugin: { enabled: true, key: "plugin-demo-1" },
    },
    filters: {
      ...DEFAULT_FILTERS,
      includeTags: ["shopify"],
      minSpent: 1000,
      maxProposals: 15,
    },
    weights: { ...DEFAULT_WEIGHTS },
    lastRunAt: null,
    lastResultCount: null,
  },
  {
    id: "radar-3",
    name: "Stripe + Webhooks",
    status: "active",
    schedule: { frequency: "realtime" },
    notifications: {
      email: { enabled: true, to: "alerts@example.com" },
      plugin: { enabled: true, key: "plugin-demo-2" },
    },
    filters: {
      ...DEFAULT_FILTERS,
      includeTags: ["stripe", "webhooks"],
      minHireRate: 50,
      maxProposals: 20,
    },
    weights: { ...DEFAULT_WEIGHTS },
    lastRunAt: null,
    lastResultCount: null,
  },
];

export const seedJobs: Job[] = [
  {
    id: "job-1",
    title: "GHL automation + Make scenario fixes",
    url: "https://www.upwork.com/job/ghl-automation",
    created_at: "2026-02-04T08:00:00Z",
    proposals: 4,
    is_payment_verified: true,
    total_spent: 25000,
    hire_rate: 63,
    experience: "Intermediate",
    country: "United States",
    budget: { type: "hourly", min: 25, max: 60 },
    normalized_stack: ["ghl", "make", "zapier"],
  },
  {
    id: "job-2",
    title: "Shopify theme CSS polish",
    url: "https://www.upwork.com/job/shopify-css",
    created_at: "2026-02-03T11:00:00Z",
    proposals: 12,
    is_payment_verified: false,
    total_spent: 800,
    hire_rate: 30,
    experience: "Entry",
    country: "Spain",
    budget: { type: "fixed", amount: 350 },
    normalized_stack: ["shopify", "css"],
  },
  {
    id: "job-3",
    title: "Stripe webhooks integration",
    url: "https://www.upwork.com/job/stripe-webhooks",
    created_at: "2026-02-02T15:30:00Z",
    proposals: 3,
    is_payment_verified: true,
    total_spent: 60000,
    hire_rate: 78,
    experience: "Expert",
    country: "Canada",
    budget: { type: "hourly", min: 60, max: 120 },
    normalized_stack: ["stripe", "webhooks", "node"],
  },
  {
    id: "job-4",
    title: "Quick Shopify bugfix",
    url: "https://www.upwork.com/job/shopify-bugfix",
    created_at: "2026-01-30T10:00:00Z",
    proposals: 7,
    is_payment_verified: true,
    total_spent: 1200,
    hire_rate: 45,
    experience: "Intermediate",
    country: "Poland",
    budget: { type: "fixed", amount: 220 },
    normalized_stack: ["shopify", "liquid", "bugfix"],
  },
  {
    id: "job-5",
    title: "Zapier + Make workflows cleanup",
    url: "https://www.upwork.com/job/make-cleanup",
    created_at: "2026-02-01T09:00:00Z",
    proposals: null,
    is_payment_verified: true,
    total_spent: 100000,
    hire_rate: 82,
    experience: "Expert",
    country: "Germany",
    budget: { type: "hourly", min: 35, max: 90 },
    normalized_stack: ["make", "zapier", "automation"],
  },
  {
    id: "job-6",
    title: "Stripe billing issue investigation",
    url: "https://www.upwork.com/job/stripe-billing",
    created_at: "2026-01-29T12:00:00Z",
    proposals: 18,
    is_payment_verified: true,
    total_spent: 4200,
    hire_rate: 55,
    experience: "Intermediate",
    country: "United Kingdom",
    budget: { type: "fixed", amount: 750 },
    normalized_stack: ["stripe", "billing"],
  },
  {
    id: "job-7",
    title: "Make scenario monitoring",
    url: "https://www.upwork.com/job/make-monitoring",
    created_at: "2026-02-04T06:30:00Z",
    proposals: 2,
    is_payment_verified: false,
    total_spent: null,
    hire_rate: null,
    experience: null,
    country: "Romania",
    budget: { type: "hourly", min: 15, max: 35 },
    normalized_stack: ["make", "monitoring"],
  },
  {
    id: "job-8",
    title: "Shopify checkout customization",
    url: "https://www.upwork.com/job/shopify-checkout",
    created_at: "2026-02-02T20:00:00Z",
    proposals: 22,
    is_payment_verified: true,
    total_spent: 30000,
    hire_rate: 60,
    experience: "Expert",
    country: "United States",
    budget: { type: "hourly", min: 40, max: 90 },
    normalized_stack: ["shopify", "checkout", "javascript"],
  },
  {
    id: "job-9",
    title: "Stripe webhook retries",
    url: "https://www.upwork.com/job/stripe-retries",
    created_at: "2026-01-25T10:00:00Z",
    proposals: 8,
    is_payment_verified: false,
    total_spent: 200,
    hire_rate: 20,
    experience: "Entry",
    country: "India",
    budget: { type: "fixed", amount: 120 },
    normalized_stack: ["stripe", "webhooks", "python"],
  },
  {
    id: "job-10",
    title: "GHL landing page fixes",
    url: "https://www.upwork.com/job/ghl-landing",
    created_at: "2026-02-03T07:30:00Z",
    proposals: 6,
    is_payment_verified: true,
    total_spent: 9000,
    hire_rate: 65,
    experience: "Intermediate",
    country: "Canada",
    budget: { type: "fixed", amount: 600 },
    normalized_stack: ["ghl", "landing", "css"],
  },
  {
    id: "job-11",
    title: "Shopify app debugging",
    url: "https://www.upwork.com/job/shopify-app",
    created_at: "2026-01-31T16:00:00Z",
    proposals: 4,
    is_payment_verified: true,
    total_spent: 150000,
    hire_rate: 88,
    experience: "Expert",
    country: "United States",
    budget: { type: "hourly", min: 90, max: 150 },
    normalized_stack: ["shopify", "node", "graphql"],
  },
  {
    id: "job-12",
    title: "Make + GHL onboarding automations",
    url: "https://www.upwork.com/job/ghl-onboarding",
    created_at: "2026-02-04T04:30:00Z",
    proposals: 1,
    is_payment_verified: true,
    total_spent: 20000,
    hire_rate: 72,
    experience: "Intermediate",
    country: "Netherlands",
    budget: { type: "hourly", min: 30, max: 70 },
    normalized_stack: ["ghl", "make", "crm"],
  },
  {
    id: "job-13",
    title: "Stripe subscription migration",
    url: "https://www.upwork.com/job/stripe-migrate",
    created_at: "2026-01-28T09:15:00Z",
    proposals: 9,
    is_payment_verified: true,
    total_spent: 52000,
    hire_rate: 59,
    experience: "Expert",
    country: "France",
    budget: { type: "fixed", amount: 2400 },
    normalized_stack: ["stripe", "subscription", "webhooks"],
  },
  {
    id: "job-14",
    title: "Make scenario optimization",
    url: "https://www.upwork.com/job/make-optimization",
    created_at: "2026-02-02T14:00:00Z",
    proposals: 5,
    is_payment_verified: true,
    total_spent: 4000,
    hire_rate: 52,
    experience: "Intermediate",
    country: "Italy",
    budget: { type: "hourly", min: 25, max: 50 },
    normalized_stack: ["make", "automation"],
  },
  {
    id: "job-15",
    title: "Shopify speed improvements",
    url: "https://www.upwork.com/job/shopify-speed",
    created_at: "2026-02-01T05:30:00Z",
    proposals: 16,
    is_payment_verified: true,
    total_spent: 10000,
    hire_rate: 46,
    experience: "Intermediate",
    country: "Poland",
    budget: { type: "fixed", amount: 950 },
    normalized_stack: ["shopify", "performance"],
  },
  {
    id: "job-16",
    title: "Stripe dispute webhooks",
    url: "https://www.upwork.com/job/stripe-dispute",
    created_at: "2026-02-03T02:00:00Z",
    proposals: 10,
    is_payment_verified: true,
    total_spent: null,
    hire_rate: null,
    experience: null,
    country: "United States",
    budget: { type: "hourly", min: 50, max: 90 },
    normalized_stack: ["stripe", "webhooks"],
  },
  {
    id: "job-17",
    title: "GHL workflow audit",
    url: "https://www.upwork.com/job/ghl-audit",
    created_at: "2026-01-29T21:00:00Z",
    proposals: 14,
    is_payment_verified: false,
    total_spent: 1500,
    hire_rate: 40,
    experience: "Entry",
    country: "Mexico",
    budget: { type: "fixed", amount: 180 },
    normalized_stack: ["ghl", "audit"],
  },
  {
    id: "job-18",
    title: "Shopify bundle feature",
    url: "https://www.upwork.com/job/shopify-bundle",
    created_at: "2026-02-04T01:00:00Z",
    proposals: 3,
    is_payment_verified: true,
    total_spent: 70000,
    hire_rate: 75,
    experience: "Expert",
    country: "Canada",
    budget: { type: "hourly", min: 80, max: 140 },
    normalized_stack: ["shopify", "bundle", "react"],
  },
  {
    id: "job-19",
    title: "Stripe webhook backlog cleanup",
    url: "https://www.upwork.com/job/stripe-backlog",
    created_at: "2026-02-02T08:00:00Z",
    proposals: 6,
    is_payment_verified: true,
    total_spent: 400,
    hire_rate: 35,
    experience: "Intermediate",
    country: "Poland",
    budget: null,
    normalized_stack: ["stripe", "webhooks", "node"],
  },
  {
    id: "job-20",
    title: "Make + Shopify automation",
    url: "https://www.upwork.com/job/make-shopify",
    created_at: "2026-02-03T13:00:00Z",
    proposals: 9,
    is_payment_verified: true,
    total_spent: 18000,
    hire_rate: 62,
    experience: "Intermediate",
    country: "Germany",
    budget: { type: "hourly", min: 35, max: 75 },
    normalized_stack: ["make", "shopify"],
  },
  {
    id: "job-21",
    title: "Stripe billing dashboard",
    url: "https://www.upwork.com/job/stripe-dashboard",
    created_at: "2026-02-01T18:30:00Z",
    proposals: 13,
    is_payment_verified: true,
    total_spent: 22000,
    hire_rate: 54,
    experience: "Intermediate",
    country: "United Kingdom",
    budget: { type: "fixed", amount: 1500 },
    normalized_stack: ["stripe", "dashboard", "react"],
  },
  {
    id: "job-22",
    title: "Shopify product page redesign",
    url: "https://www.upwork.com/job/shopify-redesign",
    created_at: "2026-02-02T05:00:00Z",
    proposals: 5,
    is_payment_verified: false,
    total_spent: 2000,
    hire_rate: 48,
    experience: "Intermediate",
    country: "Italy",
    budget: { type: "fixed", amount: 480 },
    normalized_stack: ["shopify", "design"],
  },
  {
    id: "job-23",
    title: "GHL + Make integration support",
    url: "https://www.upwork.com/job/ghl-support",
    created_at: "2026-02-04T03:00:00Z",
    proposals: 2,
    is_payment_verified: true,
    total_spent: 5000,
    hire_rate: 58,
    experience: "Intermediate",
    country: "United States",
    budget: { type: "hourly", min: 30, max: 70 },
    normalized_stack: ["ghl", "make"],
  },
  {
    id: "job-24",
    title: "Stripe webhook error handling",
    url: "https://www.upwork.com/job/stripe-errors",
    created_at: "2026-01-27T09:00:00Z",
    proposals: 11,
    is_payment_verified: true,
    total_spent: 9500,
    hire_rate: 69,
    experience: "Expert",
    country: "Canada",
    budget: { type: "hourly", min: 55, max: 110 },
    normalized_stack: ["stripe", "webhooks", "python"],
  },
];

export const seedApplications: Application[] = [
  {
    jobId: "job-2",
    status: "applied",
    note: "Sent quick estimate and timeline.",
    proposalLink: "https://docs.example.com/proposal-1",
    updatedAt: new Date().toISOString(),
  },
  {
    jobId: "job-6",
    status: "declined",
    note: "Budget too low.",
    proposalLink: "",
    updatedAt: new Date().toISOString(),
  },
  {
    jobId: "job-11",
    status: "shortlisted",
    note: "Waiting for client response.",
    proposalLink: "https://docs.example.com/proposal-2",
    updatedAt: new Date().toISOString(),
  },
];
