import JobCalendar from "./oldCharts/JobCalendar";
import JobsByCountry from "./oldCharts/JobsByCountry";

export { default as JobsChart } from "./oldCharts/JobsChart";
export { default as CountryJobsChart } from "./oldCharts/CountryJobsChart";
export { default as ExperiencePieChart } from "./oldCharts/ExperiencePieChart";
export { default as HourlyRateChart } from "./oldCharts/HourlyRateChart";
export { default as ClientRatingVsAverageRateChart } from "./oldCharts/ClientRatingVsAverageRateChart";
export { default as ClientSpendingByIndustryChart } from "./oldCharts/ClientSpendingByIndustryChart";
export { default as AverageRateByCountryChart } from "./oldCharts/AverageRateByCountryChart";
export { default as JobsOverTimeChart } from "./oldCharts/JobsOverTimeChart";
export { default as TopSkillsChart } from "./oldCharts/TopSkillsChart";
export { default as SkillsWordCloud } from "./oldCharts/SkillsWordCloud";
export { default as SkillsAverageRateChart } from "./oldCharts/SkillsAverageRateChart";
export { default as SkillsStackedBarChart } from "./oldCharts/SkillsStackedBarChart";
export { default as SkillsBubbleChart } from "./oldCharts/SkillsBubbleChart";
export { default as SkillsPieChart } from "./oldCharts/SkillsPieChart";
export { default as SkillsTreeMapChart } from "./oldCharts/SkillsTreeMapChart";
export { default as JobStats } from "./oldCharts/JobStats";
export { default as JobsByAverageRateChart } from "./oldCharts/JobsByAverageRateChart";
export { default as JobsByFixedPriceChart } from "./oldCharts/JobsByFixedPriceChart";
export { default as JobsByHourlyRateRangeChart } from "./oldCharts/JobsByFixedPriceChart";
export { default as JobsByStackedAreaChart } from "./oldCharts/JobsByStackedAreaChart";
export { default as JobsByBinnedRangeChart } from "./oldCharts/JobsByBinnedRangeChart";
export { default as JobsByRateDistributionChart } from "./oldCharts/JobsByRateDistributionChart";
export { default as AverageRateByCountry } from "./oldCharts/AverageRateByCountry";
export { default as AverageRateByExperience } from "./oldCharts/AverageRateByExperience";
export { default as JobsByExperienceLevel } from "./oldCharts/JobsByExperienceLevel";
export { default as TopSkills } from "./oldCharts/TopSkills";
export { default as SkillBadges } from "./oldCharts/SkillBadges";
export { default as AvgMinMaxJobRatesByCountry } from "./oldCharts/AvgMinMaxJobRatesByCountry";
export { default as JobRatesByCountryMinMax } from "./oldCharts/JobRatesByCountryMinMax";
export { default as JobRatesByCountryAvg } from "./oldCharts/JobRatesByCountryAvg";
export { default as JobRatesByCountryAvg2 } from "./oldCharts/JobRatesByCountryAvg2";
export { default as JobRatesByCountryMed } from "./oldCharts/JobRatesByCountryMed";
export { default as JobCalendar } from "./oldCharts/JobCalendar";
export { default as JobsByCountry } from "./oldCharts/JobsByCountry";
export { default as KeywordFrequency } from "./oldCharts/KeywordFrequency";
export { default as Tile } from "./oldCharts/Tile";
export { default as PaymentTypeChart } from "./oldCharts/PaymentTypeChart";
export { default as JobDetails } from "./JobDetails";
export { default as InstrumentBadges } from "./oldCharts/InstrumentBadges";
export { default as TopInstrumentsByAverageRate } from "./oldCharts/TopInstrumentsByAverageRate";
export { default as JobsByIndustryChart } from "./oldCharts/JobsByIndustryChart";

export * from "./elements";
