export const semanticColors = {
  background: "hsl(var(--background))",
  foreground: "hsl(var(--foreground))",
  surface: "hsl(var(--surface))",
  surfaceSubtle: "hsl(var(--surface-subtle))",
  surfaceMuted: "hsl(var(--surface-muted))",
  border: "hsl(var(--border))",
  borderSubtle: "hsl(var(--border-subtle))",
  borderStrong: "hsl(var(--border-strong))",
  primary: "hsl(var(--primary))",
  primaryHover: "hsl(var(--primary-hover))",
  primaryForeground: "hsl(var(--primary-foreground))",
  action: "hsl(var(--action))",
  actionHover: "hsl(var(--action-hover))",
  actionMuted: "hsl(var(--action-muted))",
  actionForeground: "hsl(var(--action-foreground))",
  textPrimary: "hsl(var(--text-primary))",
  textSecondary: "hsl(var(--text-secondary))",
  textMuted: "hsl(var(--text-muted))",
  textPlaceholder: "hsl(var(--text-placeholder))",
  success: "hsl(var(--success))",
  successForeground: "hsl(var(--success-foreground))",
  successMuted: "hsl(var(--success-muted))",
  warning: "hsl(var(--warning))",
  warningMuted: "hsl(var(--warning-muted))",
  destructive: "hsl(var(--destructive))",
  destructiveMuted: "hsl(var(--destructive-muted))",
} as const;

export type SemanticColor = keyof typeof semanticColors;
